### ISSUE TITLE
How to control the position of labels?

### ISSUE THREAD

**Issue by oovm** [jkuczm/mmacells#35]
Is there any options to control the position of label, like this:
XXXX  In[ ]: XXXX Code  ->  XX ln[]: XXXX Code

A small question:
The counter will not reset when I start a new Chapter in the {book}.
Now I use [index=1] to reset, but I think it can be auto reseted.

**Comment by jkuczm** [comment]
> Is there any options to control the position of label, like this:
XXXX In[ ]: XXXX Code -> XX ln[]: XXXX Code

This is (indirectly) controlled by`leftmargin` option. Its default value is `4.8em`. You can either set it in specific cell, or set it globally using `\mmaSet`.

```tex
\documentclass[12pt]{article}
\usepackage{mmacells}

\begin{document}

\noindent reference text

\begin{mmaCell}{Input}
a+b
\end{mmaCell}

\begin{mmaCell}[leftmargin=3.5em]{Input}
a+b
\end{mmaCell}

\mmaSet{leftmargin=3.5em}

\begin{mmaCell}{Input}
a+b
\end{mmaCell}

\end{document}
```
![print screen of PDF](https://cloud.githubusercontent.com/assets/4525409/22404008/5e00c25c-e627-11e6-94bd-83ffd276603d.png)

I used word "indirectly" because there are really three dimensions involved:
```
    leftmargin
        |
 ---------------
|               |
    In[12]:     code
    |     |     |
     ----- -----
       |     |
   labelwidth|
          labelsep
```
 `leftmargin` option directly controls position of code. `labelsep` option controls space separating label from code. `labelwidth` is the actual width of label. If label is too large to fit in left margin, then code  is moved to the next line, similarly to what happens in *Mathematica* FrontEnd.

**Comment by jkuczm** [comment]
> The counter will not reset when I start a new Chapter in the {book}.
Now I use [index=1] to reset, but I think it can be auto reseted.

You need to somehow add `\mmaSet{index=1}` to `\chapter` command.
Simplest way, I can think of, is using `\pretocmd` from `etoolbox` package:
```tex
\usepackage{etoolbox}
\pretocmd{\chapter}{\mmaSet{index=1}}{}{}
```
There are also specialized packages and other ways of changing behavior of sectioning commands, you can find many of them in answers to [Change size of section, subsection, subsubsection, paragraph and subparagraph title](http://tex.stackexchange.com/q/59726/70587) post on TeX StackExchange.

**Comment by oovm** [comment]
Thank for your patient answers!
