### ISSUE TITLE
Adding Caption

### ISSUE THREAD

**Issue by abduld** [jkuczm/mmacells#38]
Is there a way to add a caption using this package. I am trying this code

```
\begin{mmaCell}[
  label=,
  linkbuiltin=List,
  pattern={fun, arg, c, len},
  moredefined={RandomReal},
  caption={My Caption}
]{Input}
fun = Function[{len}, 
    NestList[
      Function[{c},
        Module[{arg = RandomReal[{0., 2. Pi}]},
          {Sin[arg], Cos[arg]}
        ] + c
    ],
    {0., 0.},
    len
]];
\end{mmaCell}

```

**Comment by jkuczm** [comment]
`mmaCell` is based on [fancyvrb](https://ctan.org/pkg/fancyvrb)s `Verbatim` environment. You can use `morefv` key to pass options directly to `Verbatim` environment. `Verbatim` offers simple captions with its `label` option (see section 4.1.7 of [fancyvrb documentation](http://mirrors.ctan.org/macros/latex/contrib/fancyvrb/doc/fancyvrb-doc.pdf)).

Note also that `Input` cell style allows formatting commands, which means that `{` and `}` characters need to be escaped. Since above cell is not using any formatting commands, you might be better served by `Code` cell style.

`linkbuiltin` works only for identifiers that appear verbatim in a cell. While there are `List`s in your code, `List` identifier doesn't appear there, so `linkbuiltin=List` option is not used. It would work for identifiers that do appear like `NestList`.

``` tex
\documentclass[12pt]{article}
\usepackage{lmodern}
\usepackage{mmacells}

\begin{document}

\begin{mmaCell}[
  label=,
  linkbuiltin=NestList,
  pattern={fun, arg, c, len},
  moredefined={RandomReal},
  morefv={frame=topline,framerule=0pt,framesep=1em,label=\textnormal{My Caption}}
]{Code}
fun = Function[{len}, 
    NestList[
      Function[{c},
        Module[{arg = RandomReal[{0., 2. Pi}]},
          {Sin[arg], Cos[arg]}
        ] + c
    ],
    {0., 0.},
    len
]];
\end{mmaCell}

\end{document}
```
![PDF output](https://user-images.githubusercontent.com/4525409/62834840-0b092680-bc52-11e9-9575-a58776785ba1.png)

**Comment by abduld** [comment]
great. thanks
